    CREATE SEQUENCE SEQ_CUIDABOT_EMPRESA START WITH 1 INCREMENT BY 1;

    CREATE TABLE T_CUIDABOT_EMPRESA (
        id NUMBER PRIMARY KEY,
        nome VARCHAR2(100) NOT NULL,
        cnpj VARCHAR2(14) NOT NULL UNIQUE,
        setor VARCHAR2(80) NOT NULL
    );

    CREATE SEQUENCE SEQ_CUIDABOT_ACAO_ESG START WITH 1 INCREMENT BY 1;

    CREATE TABLE T_CUIDABOT_ACAO_ESG (
        id NUMBER PRIMARY KEY,
        titulo VARCHAR2(100) NOT NULL,
        descricao VARCHAR2(500) NOT NULL,
        categoria VARCHAR2(50) NOT NULL,
        responsavel VARCHAR2(100) NOT NULL,
        status VARCHAR2(30) NOT NULL,
        data_inicio DATE NOT NULL,
        data_fim DATE,
        empresa_id NUMBER NOT NULL,
        CONSTRAINT FK_ACAO_EMPRESA FOREIGN KEY (empresa_id)
            REFERENCES T_CUIDABOT_EMPRESA(id)
    );

    CREATE SEQUENCE SEQ_CUIDABOT_RELATORIO_ESG START WITH 1 INCREMENT BY 1;

    CREATE TABLE T_CUIDABOT_RELATORIO_ESG (
        id NUMBER PRIMARY KEY,
        descricao VARCHAR2(500) NOT NULL,
        indicador VARCHAR2(100) NOT NULL,
        resultado VARCHAR2(300) NOT NULL,
        data_relatorio DATE NOT NULL,
        empresa_id NUMBER NOT NULL,
        CONSTRAINT FK_RELATORIO_EMPRESA FOREIGN KEY (empresa_id)
            REFERENCES T_CUIDABOT_EMPRESA(id)
    );